### ISSUE TITLE
Source Code for the connector

### ISSUE THREAD

**Issue by prestonmcgowan** [markteehan/file-chunk-connectors#2]
I see the built files have been uploaded.
May the source also be uploaded?
I am interested in the implementation and CVE patching.
Thank you.

**Comment by markteehan** [comment]
Hello Preston, 
The source-code is not available for these connectors. Although the README contains some details on operation; if you let me know what still remains vague, I'll provide more details.  On CVE patching: I am also happy to address this: let me know your expectations.

thanks
